package rest

const (
	Root                      = "/"
	Ping                      = "/ping"
	Invoice                   = "/invoice"
	InvoiceBulk               = "/invoice/bulk"
	InvoiceQuery              = "/invoice/query"
	InvoiceDetails            = "/invoice/details"
	InvoiceDetailsBulk        = "/invoice/details/bulk"
	DebitNote                 = "/debitnote"
	DebitNoteBulk             = "/debitnote/bulk"
	DebitNoteQuery            = "/debitnote/query"
	DebitNoteDetails          = "/debitnote/details"
	DebitNoteDetailsBulk      = "/debitnote/details/bulk"
	CreditNote                = "/creditnote"
	CreditNoteBulk            = "/creditnote/bulk"
	CreditNoteQuery           = "/creditnote/query"
	CreditNoteDetails         = "/creditnote/details"
	CreditNoteDetailsBulk     = "/creditnote/details/bulk"
	AuthLogin                 = "/auth/login"
	AuthRegistration          = "/auth/registration"
	AuthRefreshToken          = "/auth/refresh"
	DefineXOjanaRoute         = "/x-ojana-route/define"
	InvoiceDetailsQuery       = "/invoice/details/query"
	InvoiceDetailsBulkQuery   = "/invoice/details/bulk/query"
	DebitNoteDetailsQuery     = "/debitnote/details/query"
	DebitNoteDetailsBulkQuery = "/debitnote/details/bulk/query"
	CreditNoteDetailsBulkPost = "/creditnote/details/bulk"
	CreditNoteDetailsBulkPut  = "/creditnote/details/bulk"
	CreditNoteDetailsBulkDel  = "/creditnote/details/bulk"
	CreditNoteDetailsQuery    = "/creditnote/details/query"
)
